title: RisingTides: Sink or Swim
description: A choose your own adventure novel.
url: "https://dorsadanesh.github.io/RisingTides-Sink-or-Swim/index.html" 

remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
